name: S3 + CloudFront

on:
  push:
    branches: [ main ]

env:
  NODE_VERSION: 20.x
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: SWP391

    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install deps
        run: |
          if [ -f package-lock.json ]; then npm ci; else npm i; fi

      - name: Build
        run: |
          set -e
          npm run build
          found=""
          for d in dist build out; do
            if [ -d "$d" ]; then found="$d"; break; fi
          done
          if [ -z "$found" ]; then echo "No dist/build/out found"; exit 1; fi
          echo "DIST_DIR=$found" >> $GITHUB_ENV

      - name: Configure AWS (OIDC AssumeRole)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/${{ secrets.ROLE_GITHUB_ACTION }}
          aws-region: ${{ secrets.AWS_REGION }}
          role-session-name: gha-frontend-deploy

      - name: Sync to S3 (immutable assets)
        run: |
          aws s3 sync "$DIST_DIR" "s3://${{ secrets.S3_BUCKET }}/" \
            --delete \
            --cache-control max-age=31536000,public \
            --exclude index.html

      - name: Upload index.html (no-cache)
        run: |
          aws s3 cp "$DIST_DIR/index.html" "s3://${{ secrets.S3_BUCKET }}/index.html" \
            --cache-control max-age=0,no-cache,no-store,must-revalidate

      - name: Invalidate CloudFront
        run: |
          aws cloudfront create-invalidation \
            --distribution-id "${{ secrets.CF_DIST_ID }}" \
            --paths "/*"
